### PR TITLE
Support extra headers

### PR DESCRIPTION
**Pull request by brianary**
Adds support for additional headers.

### CODE REVIEW

**Comment by stefanstranger** [comment]
Hi @brianary so sorry I've not responded to this PR. I totally missed this. No excuse!

If I understand correctly you would want me to add headers when creating a json webtoken so you can add metadata the json webtoken?

https://auth0.com/docs/tokens/references/jwt-structure

/Stefan

**Comment by stefanstranger** [comment]
I'll update the module with your header options when a new release of the jwt nuget package is released because that contains a new method to decodeheader info. Which I'll add as a switch option for the ConvertFrom-Json function so you can also decode header info.

See for more info: https://github.com/jwt-dotnet/jwt/issues/276

**Comment by brianary** [comment]
Great, thanks!

**Comment by stefanstranger** [comment]
Hi @brianary I added extra functionality to the psjwt module. You can now add and decode header info. 

You can download the latest version (1.0.3) from the PowerShell Gallery.

Enjoy!

/Stefan

**Pull request merged**
